### ISSUE TITLE
Add Thousands Separator

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.election_day#1]
![kanton_zurich__wahlen___abstimmungen](https://cloud.githubusercontent.com/assets/186856/8326398/4f06f822-1a61-11e5-9d85-89fc0b2288f6.jpg)

**Comment by href** [comment]
Since this is a locale-dependent setting like the date format, I'll have to add this to `onegov.core` first.

**Comment by href** [comment]
Done.
