### ISSUE TITLE
Add Password Reset

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.election_day#131]

**Comment by href** [comment]
FYI, onegov.org does this already. Maybe there's some room for consolidating org's and your approach into onegov.user.

See
https://github.com/OneGov/onegov.org/blob/master/onegov/org/views/reset_password.py
https://github.com/OneGov/onegov.user/blob/master/onegov/user/auth.py
https://github.com/OneGov/onegov.user/tree/master/onegov/user/forms
