### ISSUE TITLE
Add Link to External Website

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.election_day#20]
Add the link to the external website of the canton: e.g. https://www.gr.ch/DE/publikationen/abstimmungenwahlen/

![kanton_graubunden__wahlen___abstimmungen](https://cloud.githubusercontent.com/assets/186856/11741013/9ae08cca-9ff6-11e5-9d0e-8adf5e408f74.jpg)

**Comment by href** [comment]
Can the text just be "Kanton Graubünden"? Otherwise we have to add a translatable text just for this.

**Comment by href** [comment]
Or maybe just 'www.gr.ch'?

**Comment by href** [comment]
We should change this to 'www.gr.ch' to avoid saying "Kanton Graubünden" too much. That is we just use the domain used in the link.
