### ISSUE TITLE
Add Support for Years 2010-2012

### ISSUE THREAD

**Issue by href** [OneGov/onegov.election_day#22]
This should be no problem as we have the mapdata for it:
https://github.com/interactivethings/swiss-maps/tree/master/src/swissBOUNDARIES3D

Pre-2010 years cannot be supported quite so easily.

**Comment by href** [comment]
It's unclear as of yet if we're going to be able to add these records any time soon:
https://github.com/interactivethings/swiss-maps/issues/21

**Comment by msom** [comment]
@href any updates on this issue?

**Comment by href** [comment]
No. The data is not available to us at this point. If we can somehow do it on our own that would be great though we'd have to learn a thing or to about GIS ;)

**Comment by msom** [comment]
The data for the canton of St.Gallen is now available for the years 2004-2017 (see https://github.com/OneGov/onegov.election_day/commit/9b61babf4baf697e0462c0c59a7086d6836c797a). We can still add older data for the other cantons if they want to and provide us the data (converting Shape files to Topo/GeoJSON for example is quite easy with https://www.npmjs.com/package/topojson).
