### ISSUE TITLE
Some XLSX Exports Do Not Work

### ISSUE THREAD

**Issue by href** [OneGov/onegov.election_day#25]
Oddly enough, this only fails if Romansh is selected:
https://abstimmungen.gr.ch/vote/bundesbeschluss-uber-die-anderung-der-verfassungsbestimmung-zur-fortpflanzungsmedizin-und-gentechnologie-im-humanbereich-praimplantationsdiagnostik/xlsx

**Comment by msom** [comment]
I think that's due to characters in the title of the vote (https://github.com/OneGov/onegov.election_day/blob/master/onegov/election_day/views/vote.py#L40).

**Comment by href** [comment]
In this case I would run the title through onegov.core.utils.normalize_for_url.
