### ISSUE TITLE
XLSX Import by Sheetname

### ISSUE THREAD

**Issue by href** [OneGov/onegov.election_day#26]
When importing from an XLSX file we fetch the first sheet we find. To give users more flexibility we need to add the following rule:

If a sheet with the name 'Results' or 'Resultate' is found, that sheet is used instead of the first sheet.

This is related to maintlog 5291 and #24

**Comment by msom** [comment]
See also https://github.com/OneGov/onegov.core/commit/f188f3898aca64876aba05a92c1ced83afe9b504
