### ISSUE TITLE
Mobile View Optimizations

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.election_day#34]
- Title fonts smaller
- Unfold sections

**Comment by msom** [comment]
Not sure about the font sizes, looks ok to me (foundation defaults)...

**Comment by href** [comment]
Have a look at `$h1-font-reduction` in Zurb Foundation for this. You could possibly increase that.
It's used as follows:

``` sass
font-size: $h1-font-size - $h1-font-reduction;
```

So you might be able to simply increase this value in election_day_theme.py to get a smaller font on mobile.
