### ISSUE TITLE
Panaschierstatistik

### ISSUE THREAD

**Issue by freinhard** [OneGov/onegov.election_day#37]
http://claudermont.ch/2015/10/panaschierstatistik-graubuenden-2015/

**Comment by freinhard** [comment]
<img width="764" alt="panaschierstatistik" src="https://cloud.githubusercontent.com/assets/186856/13728421/27e5b8c4-e918-11e5-9192-a8823e17743c.png">

**Comment by cdermont** [comment]
Umsetzung: http://bl.ocks.org/cdermont/846051eb548e846eac60

**Comment by msom** [comment]
![screen shot 2016-12-19 at 13 53 26](https://cloud.githubusercontent.com/assets/5045627/21313504/893cb354-c5f2-11e6-9013-ec609465199e.png)
