### ISSUE TITLE
Expats

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.election_day#40]
Where to put the expats (e.g. in the map)?

**Comment by freinhard** [comment]
What about adding a world map icon and coloring it?

http://fontawesome.io/icon/globe/
![bildschirmfoto_2016-09-14_um_16_09_30](https://cloud.githubusercontent.com/assets/186856/18515984/9cbf50cc-7a97-11e6-98a8-8158d8f59f56.jpg)
<img width="310" alt="bildschirmfoto 2016-09-14 um 16 23 51" src="https://cloud.githubusercontent.com/assets/186856/18515993/a6c0518e-7a97-11e6-9161-f34f08e3c73f.png">

**Comment by msom** [comment]
The expats can now be imported as a separate entity/municipality/district using all the formats (if the ID is `0` or one of the special, reserved BFS numbers for expats) and are shown in the results as distinct a row. Internally, we set `entity_id = 0` and use the group name provided when importing.

Further improvements would be:
- [x] Don't use the given group name, use a fixed, translated string
- [x] ~~Highlight the expat row in the table (sticky and italic?)~~
- [x] Show the expats in the map (propably after the JavaScript has been refactored for #51)

**Comment by msom** [comment]
![screen shot 2017-04-24 at 14 40 33](https://cloud.githubusercontent.com/assets/5045627/25337394/00845b3a-28fc-11e7-853f-dacee24c6125.png)
