### ISSUE TITLE
Improve Print Styles

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.election_day#52]

**Comment by msom** [comment]
https://github.com/OneGov/onegov.election_day/commit/f58b566ba4fe766ffc0eb67d38973b4d9a3a859a

**Comment by freinhard** [comment]
To be improved in Safari.

![bildschirmfoto 2016-09-07 um 18 37 30](https://cloud.githubusercontent.com/assets/186856/18320479/51fc23fc-752a-11e6-8152-df2f304b38fc.png)
