### ISSUE TITLE
Add Support for Year 2017

### ISSUE THREAD

**Issue by msom** [OneGov/onegov.election_day#68]

**Comment by msom** [comment]
See
- [Amtliches Gemeindeverzeichnis der Schweiz - Mutationsmeldungen 2016](https://www.bfs.admin.ch/bfsstatic/dam/assets/1666963/master)
- [Amtliches Gemeindeverzeichnis der Schweiz - Angekündigte Änderungen 2017](https://www.bfs.admin.ch/bfsstatic/dam/assets/1666959/master)

From [Amtliches Gemeindeverzeichnis der Schweiz](https://www.bfs.admin.ch/bfs/de/home/grundlagen/agvch.html).

**Comment by href** [comment]
FYI: https://github.com/seantis/swiss-municipalities

**Comment by msom** [comment]
Municipality data added with https://github.com/seantis/swiss-municipalities/commit/286f1a42fbc3a1fa7ad80ec1b90aafef09311800 / https://github.com/OneGov/onegov.election_day/commit/bf979f638e45a4ab7f173b47423afc071240b27a. Another update is required after 2.4.2017.
