### ISSUE TITLE
Testing Takes too Long

### ISSUE THREAD

**Issue by href** [OneGov/onegov.election_day#95]
I'm trying to build [a meta-package containing all OneGov applications](https://github.com/OneGov/onegov.applications). The idea is to have a known good set of applications that all share the same dependencies.

This allows us to run various applications in the same server process, which is more efficient and is required for applications to work together properly (i.e. onegov.town and onegov.onboarding).

Unfortunately I can't include onegov.election_day in this meta-package at the moment because the tests time out:

![screenshot of safari 17-03-17 10-32-56](https://cloud.githubusercontent.com/assets/273163/24037366/db4d537e-0afd-11e7-9788-186b7dc432f1.png)

Since the time-limit for Travis jobs is around 40 minutes this is a problem that onegov.election_day itself will face soon as well. Soon tests on Travis will no longer work.

I think the goal should be to cut this time in half.

**Comment by msom** [comment]
A Python 3.4 run takes typically about less than 20':

![screen shot 2017-03-17 at 10 58 27](https://cloud.githubusercontent.com/assets/5045627/24038210/bb2f9ed2-0b00-11e7-9ab3-f20abe8b2b9f.png)

**Comment by href** [comment]
I might be unlucky with the VMs, but during my onegov.applications testing where I've tried various approaches I usually took 30' or more. Locally it takes about twice as long for my election day tests to run as my org tests, which would be more in line with the numbers you're seeing.

Still, even if we didn't have a limit on Travis, election_day takes 5.4 seconds per test on average, while org takes 2.0. I think bringing down those numbers is important. Tests are meant to run quick.

Originally I wanted to run all the applications tests in a single Travis job and that is definitely not doable at the moment. It would be if we halved the testing times in election_day.

**Comment by msom** [comment]
I strongly disagree. Tests are not meant to run quickly, they are meant to test things - I don't care how long they take, they have to cover everything I want to test.

**Comment by href** [comment]
Sure, but slow tests indicate that either the program code is slow or that the test is doing too much. 

For example, I found that the CSV parser in the core was doing way to much work for each record. So now it's much faster, improving the testing time by one minute. This of course improves the performance of all CSV imports across our products:

https://github.com/OneGov/onegov.core/commit/0fa98a7f423a69fc6608e3451e146604a50d72a3

About tests doing too much: I think these tests could be done much faster:
- test_upload_election_majorz_roundtrip
- test_upload_election_proporz_roundtrip

Together they take almost 3 minutes to run. But they don't seem to be testing the content of the CSV as such. At least they don't check the result against expected values. Instead it looks like they just want to make sure that exports can be imported.

If these tests used a smaller CSV to do this, they could do this in a few seconds. Maybe the test could sample some data from the CSV instead of reading the whole thing?

**Comment by href** [comment]
I finally fixed what I knew for a long time to be a performance issues with our tests. So far we've compiled the SCSS theme once per test function. Now we do it once per test session and the results are pretty nice across the board. Here's the updated election_day:

![screenshot of safari 17-03-17 17-32-49](https://cloud.githubusercontent.com/assets/273163/24053068/f96a3234-0b37-11e7-91cd-9d89e51e2f0a.png)

Now org takes 1.5 seconds and election_day 3.5 seconds per test on average.

**Comment by msom** [comment]
Nice! :)

**Comment by href** [comment]
Is it okay if I create a patch release of the chances I've already made? I can then include onegov.election_day in onegov.applications.

**Comment by msom** [comment]
Sure!

**Comment by msom** [comment]
With your changes and the changes from https://github.com/OneGov/onegov.election_day/commit/28f8ed6b998fe3ad045cd8a806e93e371896eee6 the tests run now a lot faster and take roughly the same amount of time per test as the other packages:

- [onegov.org 0.9.2](https://travis-ci.org/OneGov/onegov.org/jobs/244438713): 2.8s
- [onegov.election_day 1.13.2](https://travis-ci.org/OneGov/onegov.election_day/jobs/245226110): 2.6s

**Comment by href** [comment]
Awesome, thanks!
